### ISSUE TITLE
使用mysql作为图库数据存储时，每个图库都会占用连接数，且不释放的问题

### ISSUE THREAD

**Issue by fantengfeiNana** [apache/incubator-hugegraph#2668]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑设计问题)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.3.0 (Apache Release Version)
- Backend: mysql

### Your Question (问题描述)

我们在使用mysql作为hugegraph的存储方式时，在批量创建知识图谱时出现了程序提示超出了数据库最大链接数的问题，经过验证发现，知识图谱在创建完成后，且没有访问的情况下，每个知识图谱对应的数据库都会占用最低两个数据库链接。【重启 hugegrapg-server】后，链接即被占用。
![image](https://github.com/user-attachments/assets/4edac80b-95e8-44a6-b720-8a3b4a03b244)
![image](https://github.com/user-attachments/assets/fe514242-c0f9-4fdc-b8fd-10302fe5671f)
按照这个数据推送，如果数据库最大链接数为2000，只能创建约667个知识图谱，请问如何解决该问题，因为数据库链接资源有限

**Comment by imbajin** [comment]
@dosu
You should first inquire about the user's usage scenarios and methods. Under normal circumstances, it is not expected to create hundreds of graph instances on a single node, usually in single digits (you can use subgraph partitioning/permission management/tenants, etc.) for resource isolation, rather than creating a large number of graph instances. In short, it feels more like there is a gap in the background area. It is advisable to confirm it before discussing the issue of MySQL connection numbers
