### ISSUE TITLE
[Question] 创建图的时候，支持同时增加元数据吗？

### ISSUE THREAD

**Issue by insist93** [apache/incubator-hugegraph#2679]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: docker images：hugegraph/hugegraph 1.3.0

### Your Question (问题描述)

# 有没有什么方法，创建图的时候同时插入图的元素据

**Comment by imbajin** [comment]
@insist93 
Yes, `Gremlin` supports the Groovy syntax when querying, allowing for the execution of multiple statements at once, including metadata CRUD, graph data CURD, and graph queries, making it versatile

@dosu Can you give some examples of the meta-data (`VertexLabel/EdgeLable`) that created the HugeGraph graph schema in Gremlin, so that they can execute it at one time

**Comment by insist93** [comment]
> @insist93 Yes, `Gremlin` supports the Groovy syntax when querying, allowing for the execution of multiple statements at once, including metadata CRUD, graph data CURD, and graph queries, making it versatile (use `;` to separate one line)
> 
> @dosu Can you give some examples of the meta-data (`VertexLabel/EdgeLable`) that created the HugeGraph graph schema in Gremlin, so that they can execute it at one time

The meta data I mentioned above refers to meta attributes like graph_create_time, graph_owner, etc., not vertices and edges propertiyes；is there any other api？
